### PR TITLE
Add code for producing json files of skimmed samples

### PR DESCRIPTION
**Pull request by Andrew42**
This PR introduces a new analysis script called [make_skim_jsons.py](https://github.com/TopEFT/topcoffea/blob/make-skim-jsons/analysis/topEFT/make_skim_jsons.py).

The script works by being given a path to a hadoop directory (or directories) that should contain the results of a lobster skim job. For each lobster WF directory that the script finds, it will attempt to find a matching json sample file. Upon a successful match it will load the json file and replace the `files` list with the list of files from the matching lobster skim directory. The script will then save the json to a new file with '_NDSkim' appended to the file name so as to not clobber the original files. Afterwards the script will printout any skims that it could not find a matching json for, as well as any json files that it could not find a matching skim.

The PR also makes some organizational changes to the scripts introduced in PR #122. Specifically it renames the `update_jsons.py` script to `update_json_sow.py` and also moves some of the functionality out of the script and into the `utils.py` module.

Finally, the PR adds a number of skim jsons for the Run 2 datasets. Skims are available for all three data taking years and a corresponding cfg has also been added that points to these new jsons.

The skim jsons were produced by running the following command from the `topcoffea/analysis/topEFT` directory:

`python make_skim_jsons.py /hadoop/store/user/awightma/skims/NanoAOD_ULv8/v1 --json-dir ../../topcoffea/json/data_samples`

### CODE REVIEW

**Comment by Andrew42** [comment]
Please hold off on reviewing/merging this branch as I've just discovered a bug in the skimmer code. Apparently the code wasn't properly passing in the skim cut and instead of crashing like you might expect when something like this occurs:
`>> cmd: Error in <TTreeFormula::Compile>:  Bad numerical expression : "+cut=nMuon"
>> cmd: Info in <TSelectorDraw::AbortProcess>: Variable compilation failed: {,--cut=nMuon+nElectron >=2 && Sum$( Muon_looseId && Muon_miniPFRelIso_all < 0.4 && Muon_sip3d <8) + Sum$(Electron_miniPFRelIso_all < 0.4 && Electron_sip3d <8 && Electron_mvaFall17V2noIso_WPL) >=2}`

The NAOD skimmer just chugs along on its merry way and even produces a output root file. The file has no events in it, but it still gets made. So that's kind of annoying. Anyways, I need to figure out how to fix the cut issue and remake the skims before we actually merge this PR into master.

**Comment by Andrew42** [comment]
@kmohrman , @bryates I've (finally) managed to remake the skims for the full run 2 data and updated the json files appropriately. I've also made some quality of life changes to the `make_skim_jsons.py` script.

Due to the issues with trying to produce the skims all in one go, I had to split up the lobster skim making jobs based on run year. Additionally, for the UL2018 datasets I had to run an additional skim job specifically for the `DoubleMuon_D-UL2018` dataset. This is because in the original skim job that dataset (and that dataset only) had some failed/stuck tasks that never completed. 

Once I decided to redo just that specific dataset on its own, I went and removed entirely the `DoubleMuon_D-UL2018` dataset directory from the original UL2018 lobster skim job, so there should only be one copy of this dataset under `/hadoop/store/user/awightma/skims/data/NanoAOD_ULv8_UL2018` and there should be no worries about accidentally using a bad or incomplete dataset skim.

For documentation purposes, the updated json skim files were produced with the following command:
```
python make_skim_jsons.py --json-dir ../../topcoffea/json/data_samples --file ND_data_skim_locations.txt
```

This time I did check the task logs for the lobster skimming and confirmed a non-zero filter efficiency, so hopefully this time around the skims will have been produced correctly!

**Comment by kmohrman** [comment]
Thanks very much @Andrew42 for putting together this PR! It looks like it was a lot of work, but I think these skims are going to be really useful. Looking through the list of files changed, it looks like it does not modify much existing code, so would probably be pretty safe to merge.

I have not, however, attempted to process any of these skims yet. Should someone do that before we merge? @bryates, I'm wondering if you've happened to have done that already (or planned to do it), or if I should plan to check it out?

**Comment by Andrew42** [comment]
> Thanks very much @Andrew42 for putting together this PR! It looks like it was a lot of work, but I think these skims are going to be really useful. Looking through the list of files changed, it looks like it does not modify much existing code, so would probably be pretty safe to merge.
> 
> I have not, however, attempted to process any of these skims yet. Should someone do that before we merge? @bryates, I'm wondering if you've happened to have done that already (or planned to do it), or if I should plan to check it out?

I think it would be a good idea to have another person at least try to process some of these skims and cross check with what they expect the outputs to be, simply b/c I had to remake the skims once already. Having said that, the info for accessing and working with the skimmed samples (i.e. the json files) is completely independent from everything else<sup>&dagger;</sup>, so even if there were some issue with the skim samples, there's nothing stopping us from just swapping over to the full un-skimmed samples (aside from the amount of time it would take to process the full samples). We just would want to make sure that we don't take the the skimmed samples as the "gospel truth" and automatically assume they are a drop-in replacement for the full samples.

&dagger;: As I mentioned earlier having the skims connected in some way (i.e. depend on) to the samples that they are produced from might be something we want to consider. Since if the original samples change (e.g. we want to move to a newer version of NAOD) then it would be nice to know which original samples a particular skim is connected to.

**Comment by bryates** [comment]
> > Thanks very much @Andrew42 for putting together this PR! It looks like it was a lot of work, but I think these skims are going to be really useful. Looking through the list of files changed, it looks like it does not modify much existing code, so would probably be pretty safe to merge.
> > I have not, however, attempted to process any of these skims yet. Should someone do that before we merge? @bryates, I'm wondering if you've happened to have done that already (or planned to do it), or if I should plan to check it out?
> 
> I think it would be a good idea to have another person at least try to process some of these skims and cross check with what they expect the outputs to be, simply b/c I had to remake the skims once already. Having said that, the info for accessing and working with the skimmed samples (i.e. the json files) is completely independent from everything else†, so even if there were some issue with the skim samples, there's nothing stopping us from just swapping over to the full un-skimmed samples (aside from the amount of time it would take to process the full samples). We just would want to make sure that we don't take the the skimmed samples as the "gospel truth" and automatically assume they are a drop-in replacement for the full samples.
> 
> †: As I mentioned earlier having the skims connected in some way (i.e. depend on) to the samples that they are produced from might be something we want to consider. Since if the original samples change (e.g. we want to move to a newer version of NAOD) then it would be nice to know which original samples a particular skim is connected to.

I'll try to run this tomorrow. @Andrew42 can you think of some unit tests for your new code? If it's all just related to loading files from `XRootD`, we can just add your scripts to the ignore section of `codecov.yml`.

**Comment by bryates** [comment]
> > > Thanks very much @Andrew42 for putting together this PR! It looks like it was a lot of work, but I think these skims are going to be really useful. Looking through the list of files changed, it looks like it does not modify much existing code, so would probably be pretty safe to merge.
> > > I have not, however, attempted to process any of these skims yet. Should someone do that before we merge? @bryates, I'm wondering if you've happened to have done that already (or planned to do it), or if I should plan to check it out?
> > 
> > 
> > I think it would be a good idea to have another person at least try to process some of these skims and cross check with what they expect the outputs to be, simply b/c I had to remake the skims once already. Having said that, the info for accessing and working with the skimmed samples (i.e. the json files) is completely independent from everything else†, so even if there were some issue with the skim samples, there's nothing stopping us from just swapping over to the full un-skimmed samples (aside from the amount of time it would take to process the full samples). We just would want to make sure that we don't take the the skimmed samples as the "gospel truth" and automatically assume they are a drop-in replacement for the full samples.
> > †: As I mentioned earlier having the skims connected in some way (i.e. depend on) to the samples that they are produced from might be something we want to consider. Since if the original samples change (e.g. we want to move to a newer version of NAOD) then it would be nice to know which original samples a particular skim is connected to.
> 
> I'll try to run this tomorrow. @Andrew42 can you think of some unit tests for your new code? If it's all just related to loading files from `XRootD`, we can just add your scripts to the ignore section of `codecov.yml`.

I've run the example above to produce the skim files with no issues, so now I'm trying to run over the 2017 data.

**Comment by bryates** [comment]
Here are the [CR plots](http://www.crc.nd.edu/~byates2/coffea/skim/) I was able to make. I think everything looks good.

**Comment by kmohrman** [comment]
> Here are the [CR plots](http://www.crc.nd.edu/~byates2/coffea/skim/) I was able to make. I think everything looks good.

Thanks for this check @bryates! I'm wondering if you happened to compare the unskimmed data to the skimmed data directly? I think that would be a really explicit check of whether or not the skims are working as expected.

**Comment by Andrew42** [comment]
So [here](http://www.crc.nd.edu/~byates2/coffea/skim/cr_3l/cr_3l_j0eta_unitnorm.png) is a link to one of @bryates's distributions and [here](http://www.crc.nd.edu/~awightma/eft_stuff/misc/full_run2/distributions/baseline/cr_3l/j0eta.png) is a link to the same distribution I made awhile ago and at least visually the shapes of the two look very similar.

This was just the first distribution I picked, so we should probably look at the others as well and maybe do a more explicit apples-to-apples check by having the same person's framework produce the comparisons

**Comment by kmohrman** [comment]
> So [here](http://www.crc.nd.edu/~byates2/coffea/skim/cr_3l/cr_3l_j0eta_unitnorm.png) is a link to one of @bryates's distributions and [here](http://www.crc.nd.edu/~awightma/eft_stuff/misc/full_run2/distributions/baseline/cr_3l/j0eta.png) is a link to the same distribution I made awhile ago and at least visually the shapes of the two look very similar.
> 
> This was just the first distribution I picked, so we should probably look at the others as well and maybe do a more explicit apples-to-apples check by having the same person's framework produce the comparisons
> 
> Edit: It looks like there are very slight visual differences in the shapes of some distributions, but this could just be due to updates that have been made in the processor since I made those plots (they were made almost exactly 2 months ago)

Thanks @Andrew42. I agree that a more explicit check would be good (i.e. run the processor over the data from the unskimmed samples, then run it over the data from the skimmed samples, and directly compare on the same plot). I don't have time to do this today, so if someone else gets a chance, that'd be great. If no one else has time either, I'm not sure if this needs to stop us from merging, since this PR does not really affect the already-existing code. However, I do think we should hold off on using the skims for plots and other checks till we've done this direct comparison.

**Review by bryates — APPROVED** [review]
